apiVersion: v1
kind: Service
metadata:
  name: tech-challenger-service
spec:
  selector:
    app: tech-challenger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31113
  type: NodePort