apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenger-deployment
  labels:
    app: tech-challenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenger
  template:
    metadata:
      labels:
        app: tech-challenger
    spec:
      containers:
        - name: tech-challenger
          image: jonatasalvesdev/tech-challenger:2.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "development"

---

apiVersion: v1
kind: Service
metadata:
  name: tech-challenger-service
spec:
  selector:
    app: tech-challenger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer