apiVersion: v1
kind: Pod
metadata:
  name: tech-challenger
spec:
  restartPolicy: Always
  containers:
    - name: tech-challenger
      image: jonatasalvesdev/tech-challenger:2.1
      ports:
        - containerPort: 8080
      env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenger-service
spec:
  selector:
    app: tech-challenger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  type: LoadBalancer